target_compile_definitions(${PROJECT_NAME} PRIVATE
    FREERTOS_KERNEL_PATH="${FREERTOS_KERNEL_PATH}"
    PICO_FLASH_ASSUME_CORE1_SAFE=1
    APP_BUILD_VERSION="${APP_BUILD_VERSION}"
    PICO_BOARD_ACTUAL="${PICO_BOARD_ACTUAL}"
)